# Generated by Django 5.2 on 2025-04-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_alter_table_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='data',
            field=models.TextField(),
        ),
    ]
